const { Schema, model } = require('mongoose');

var validateEmail = function (email) {
    var re = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
    return re.test(email)
};

const userSchema = new Schema({

    //id : unique id will automatically be generated by mongodb correspond to _id: flied

    userName: {
        type: String,
        required: [true, 'Please add your name.']
    },

    email: {
        type: String,
        required: [true, 'Please add your email address.'],
        trim: true,
        lowercase: true,
        unique: true,
        validate : [validateEmail, "Please add a valid email address."],
        match: [/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/, 'Please fill a valid email address']
    },

    password: {
        type: String,
        required: [true, 'Please add password to protect your account'],
        minLength: [8, 'Password cannot be less than 8 characters'],
        maxLength: [64, 'Password cannot proceed 64 characters'],
        select: false, //make password protected
    },

    numberOfPosts : {
        type: Number,
        default : 0,
    },

    resetPasswordCode: {
        type: String,
    },

    resetPasswordExpire: {
        type: Date
    }

}, { timestamps: true })

module.exports = model("User", userSchema)